config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
    resources :items do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  @comment = Comment.create(text: params[:text], item_id: params[:item_id], user_id: current_user.id)
  redirect_to "/items/#{@comment.item.id}"
  end
  
  private
  def comment_params
    params.permit(:text, :item_id)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :move_to_index, except: [:index,:show]
  before_action :correct_user, only: [:edit,:update]

  def index
    @items = Item.includes(:user).order("created_at DESC").page(params[:page]).per(9)
  end
  
  def new
    @item = Item.new
  end
  
  def create
    Item.create(image: item_params[:image],item_name: item_params[:item_name], price: item_params[:price],store: item_params[:store], text: item_params[:text],user_id:current_user.id)
    redirect_to :root
  end
  
  def destroy
    item = Item.find(params[:id])
    item.destroy if item.user_id == current_user.id
    redirect_to :root
  end
  
  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params) if item.user_id == current_user.id
    redirect_to :root
  end
  
  def show
    @item = Item.find(params[:id])
    @comments = @item.comments.includes(:user)
  end
  
  private
  def item_params
    params.require(:item).permit(:content, :item_name, :price, :store, :text,:image)
  end
  
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def correct_user
    @item = Item.find(params[:id])
    if current_user != @item.user
       redirect_to root_path
    end
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @items = user.items.page(params[:page]).per(6).order("created_at DESC")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<div class="edit-form">
 <div class="center">
  <%= form_for @item do |f| %>
 <div class="caution" h4>品名、価格、店名は15文字</br>コメントは40字以内で入力して下さい</h4></div>
    <dl>
      <dt>品名</dt>
      <dd><%= f.text_field :item_name,required: true, maxlength:15, style: 'width:15em;' %></dd>
       <dt>価格(税込み）</dt> 
        <dd><%= f.number_field :price,required: true, maxlength:15, style: 'width:15em;' %>円</dd>
       <dt>店名</dt>
       <dd><%= f.text_field :store,required: true,maxlength:15, style: 'width:15em;' %></dd>
       <dt>現在の画像</dt>
       <img src="<%= @item.image %>" class="edit-img"/>
       <dt>＜画像を変更する場合は選択して下さい＞</dt>
       <dd><%= f.file_field :image %></dd>
       <dt>コメント</dt>
       <dd><%= f.text_area :text,required: true, maxlength:40, style: 'width:20em; height: 3em;'  %></dd>
    </dl>
  <div class="submit"><%= f.submit '編集' %></div>
  <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="flexbox">
  <% @items.each do |item| %>
  <div class="item">
    <img src="<%= item.image %>">
    <li>
      <ul class="item_name">品　名：<%= item.item_name %></ul>
      <ul class="price">価　格：<%= item.price %>円</ul>
      <ul class="store">購入店：<%= item.store %></ul>
    </li>
      <div class="text"><%= item.text %></div>
        <div class="more">
          <ul class="list">
            <li>
              <%= link_to '詳細', "/items/#{item.id}", method: :get %>
            </li>
            <% if user_signed_in? && current_user.id == item.user_id %>
            <li>
            <%= link_to '編集', "/items/#{item.id}/edit", method: :get %>
            </li>
            <li>
              <%= link_to '削除', "/items/#{item.id}", method: :delete,data: {confirm: "本当に削除しますか？"} %>
            </li>
            <% end %>
          </ul>
        </div>
   </div>
  <% end %>
</div>
  <%= paginate(@items) %>

app/views/items/new.html.erb
<div class="form">
  <%= form_for @item do |f| %>
<div class="caution" h4>品名、価格、店名は15文字</br>コメントは40字以内で入力して下さい</h4></div>
    <dl>
      <dt>品名</dt>
      <dd><%= f.text_field :item_name,required: true, maxlength:15, style: 'width:15em;' %></dd>
       <dt>価格(税込み）</dt> 
        <dd><%= f.number_field :price,required: true, maxlength:15, style: 'width:15em;' %>円</dd>
       <dt>店名</dt>
       <dd><%= f.text_field :store,required: true,maxlength:15, style: 'width:15em;' %></dd>
       <dt>画像</dt>
       <dd><%= f.file_field :image,required: true %></dd>
       <dt>コメント</dt>
       <dd><%= f.text_area :text,required: true, maxlength:40, style: 'width:20em; height: 3em;'  %></dd>
    </dl>
  <div class="submit"><%= f.submit '投稿' %></div>
<% end %>
</div>

app/views/items/show.html.erb
<div class="flexbox">
  <div class="user_item">
    <img src="<%= @item.image %>">
    <li>
      <ul class="item_name">品名：<%= @item.item_name %></ul>
      <ul class="price">価格：<%= @item.price %>円</ul>
      <ul class="store">購入店：<%= @item.store %></ul>
    </li>
      <div class="text"><%= simple_format(@item.text) %></div>
      
        <div class="more">
          <ul class="list">
          <% if user_signed_in? && current_user.id == @item.user_id %>
            <li>
            <%= link_to '編集', "/items/#{@item.id}/edit", method: :get %>
            </li>
            <li>
              <%= link_to '削除', "/items/#{@item.id}", method: :delete,data: {confirm: "本当に削除しますか？"} %>
            </li>
          <% end %>
            <li>
            <%= link_to '戻る', "/", method: :get %>
            </li>
          </ul>
        </div>
  </div>
    <div class="container"> 
    <% if current_user %>
      <%= form_tag("/items/#{@item.id}/comments", method: :post) do %>
      <dl>
        <dt><textarea name="text"  class="commentlines" placeholder="コメントする？(40文字まで)" rows="2" cols="40" maxlength="40"></textarea></dt>
        <dt><input type="submit" value="コメント！"></dt>
      </dl>
      <% end %>
    <% end %>
     <div class="comments">   
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuyIt・それ、買おう</title>
    <meta charset="UTF-8" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">

    <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
      <div class="main">
        <div class="title"><a href="/">それ、買おう</a></div>
        <% if user_signed_in? %>
        <div class="sign-box">
          <div class="name-nav">
            <h2>ようこそ-<%= current_user.nickname %>-さん</h2>
            <a href="/users/<%= current_user.id %>">過去の投稿</a>
            <%= link_to "投稿！",  new_item_path, class: "post-one" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"post" %>
          </div>
        </div>
        <% else %>
        <div class="sign-box">
          <div class="menu-nav">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <h3>
        Copyright buy it 2020.
      </h3>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<p class="first"><%= @nickname %>さんの過去の投稿です</p>
<div class="flexbox">
  <% @items.each do |item| %>
  <div class="item">
    <img src="<%= item.image %>">
    <li>
      <ul class="item_name">品名：<%= item.item_name %></ul>
      <ul class="price">価格：<%= item.price %>円</ul>
      <ul class="store">購入店：<%= item.store %></ul>
    </li>
      <div class="text"><%= item.text %></div>
  
        <div class="more">
          <ul class="list">
            <li>
              <%= link_to '詳細', "/items/#{item.id}", method: :get %>
            </li>
            <% if user_signed_in? && current_user.id == item.user_id %>
            <li>
            <%= link_to '編集', "/items/#{item.id}/edit", method: :get %>
            </li>
            <li>
              <%= link_to '削除', "/items/#{item.id}", method: :delete,data: {confirm: "本当に削除しますか？"} %>
            </li>
            <% end %>
          </ul>
        </div>
   </div>
  <% end %>
</div>
  <%= paginate(@items) %>